name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-artifacts.yml

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-mac
          path: release-artifacts
      - uses: actions/download-artifact@v4
        with:
          name: release-win
          path: release-artifacts
      - uses: actions/download-artifact@v4
        with:
          name: release-linux
          path: release-artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/**/*
          generate_release_notes: true
          prerelease: true
          fail_on_unmatched_files: true
